"""
Invoice Parser — LangGraph-based agentic pipeline for structured extraction.

Accepts layout-preserving text input from pdfplumber and uses Gemini to extract
structured GST invoice data. Features:
- Format-adaptive prompt for diverse Indian invoice layouts
- IGST vs CGST+SGST auto-detection from GSTIN state codes
- Self-healing with error-aware retry logic (up to 2 retries)
- Post-extraction normalization (amounts, dates, GSTINs)
- Confidence scoring for HITL review
"""
import logging
import json
import re
from typing import TypedDict, List, Optional

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_core.output_parsers import PydanticOutputParser
from langgraph.graph import StateGraph, END

from config import GOOGLE_API_KEY, STATE_CODES
from schemas import InvoiceData, LineItem, TaxDetail, SupplyType

logger = logging.getLogger(__name__)

# ──────────────────────────────────────────────
# State Definition
# ──────────────────────────────────────────────
class GraphState(TypedDict):
    raw_markdown: str
    extracted_data: Optional[dict]
    errors: List[str]
    retry_count: int
    vendor_hint: Optional[str]
    previous_errors: List[str]  # Errors from prior attempt for self-correction


# ──────────────────────────────────────────────
# System Prompt — Format-adaptive, GST-focused
# ──────────────────────────────────────────────
SYSTEM_PROMPT = """\
You are an expert Indian GST invoice processing agent.

You will receive a **layout-preserving text representation** of a digital invoice. This text
was generated by a layout-aware PDF extractor (pdfplumber) and preserves the original
spatial structure and column alignments, including:
- **Spaced tables** with aligned columns for line items, tax breakdowns, and totals.
- **Headings** for section labels.
- **Key-value pairs** for header fields (Invoice No., Date, GSTIN, etc.).

## Your Task

Extract ALL fields into the requested JSON schema. Follow these rules precisely:

### Invoice Format Variations
Indian invoices come in many formats. Handle ALL of these:
- Some invoices have **IGST only** (inter-state) — no CGST/SGST columns.
- Some invoices have **CGST + SGST** (intra-state) — no IGST column.
- Some invoices have **CESS** as an additional tax column.
- Some invoices have a **Discount** column per line item.
- Some invoices have **"Bill To"** and **"Ship To"** addresses (different parties).
- Some invoices have **Reverse Charge** declaration ("Yes"/"No" or "Y"/"N").
- Some invoices have **IRN** (Invoice Reference Number) for e-invoicing.
- Some invoices have **QR code data** printed or encoded.
- Some invoices show **Amount in Words** in Hindi or English.
- Some invoices may NOT have: bank details, transport details, e-way bill, challan,
  MSME number, or shipping address. Leave those as null.

### Supply Type Detection (CRITICAL)
Determine `supply_type` by comparing the first 2 digits of vendor GSTIN and customer GSTIN:
- **Same state code** → `supply_type = "INTRA_STATE"` (expect CGST + SGST)
- **Different state code** → `supply_type = "INTER_STATE"` (expect IGST)
- **Cannot determine** → `supply_type = "UNKNOWN"`

### Tax Handling
- Identify the **tax type** used in the invoice: **CGST + SGST** (intra-state) or **IGST** (inter-state).
- For **INTRA_STATE**: extract CGST and SGST separately. Rates are always equal (e.g., 9% + 9% = 18% GST).
- For **INTER_STATE**: extract IGST only. The IGST rate equals CGST + SGST (e.g., 18% IGST).
- Some invoices may also have **CESS** — extract it separately.
- For each line item, extract the tax rate (%) and tax amount separately for each tax type.
- Provide an aggregated `tax_breakup` at the invoice level.
- Calculate `total_cgst`, `total_sgst`, `total_igst`, `total_cess` at invoice level.

### Line Items (CRITICAL — DO NOT SKIP ANY ROW)
- Extract **EVERY product/service row** from the Markdown table. Do NOT skip any row.
- Some rows may have an **empty or missing Sr. No.** — still extract them. Auto-assign
  sequential sr_no (1, 2, 3...) if the original Sr. No. is blank.
- Ignore header rows (column names) and total/summary rows, but extract ALL product rows.
- Extract: Sr. No., Description, HSN/SAC, Qty, Unit, Rate, Discount, Taxable Value,
  Tax columns (with type and rate), and Total.
- The `taxable_value` is the amount BEFORE tax (usually qty × rate - discount).
- The `total` for each line is taxable_value + sum of all tax amounts on that line.
- If discount column exists, extract it. Otherwise set discount = 0.0.
- The number of line items must match the total quantity count if shown in the totals row.

### GSTIN and PAN Extraction
- Extract both **vendor (seller)** and **customer (buyer)** GSTIN numbers (15 chars).
- From GSTIN, derive `state_code` (first 2 digits) and `pan` (characters 3–12).
- GSTINs follow this format: 2-digit state code + 10-char PAN + 1 entity + 1 check digit + 1 Z/alphabet.

### Other Details
- Extract bank details (Bank Name, A/c No., IFSC, Branch) if present.
- Extract transport details (Transport Name, Transport ID, Vehicle No.) if present.
- Extract e-invoicing fields (IRN, Ack No., Ack Date, QR code data) if present.
- Extract `reverse_charge` as "Y" or "N" if mentioned.
- Extract `round_off` amount if the invoice rounds to nearest rupee.

### Math Consistency
- `total_taxable_amount` = sum of all line item `taxable_value` fields.
- `total_tax_amount` = sum of all tax amounts across all line items.
- `total_amount` = `total_taxable_amount` + `total_tax_amount` + `round_off`.
- `total_cgst` = sum of all CGST tax amounts.
- `total_sgst` = sum of all SGST tax amounts.
- `total_igst` = sum of all IGST tax amounts.

### Confidence Score
Provide a `confidence_score` between 0.0 and 1.0 indicating your overall confidence
in the extraction quality:
- 1.0 = all fields clearly visible and unambiguous
- 0.7–0.9 = most fields clear, some ambiguity
- 0.5–0.7 = significant portions unclear or missing
- < 0.5 = poor quality, many fields guessed or missing

If you cannot find a field, leave it as null or 0.0. **Never hallucinate data.**

{format_instructions}
"""

# ──────────────────────────────────────────────
# Retry-aware prompt (includes previous errors)
# ──────────────────────────────────────────────
RETRY_SUFFIX = """

## Previous Extraction Errors
The previous extraction attempt had these issues. Please fix them in this attempt:
{previous_errors}
"""


# ──────────────────────────────────────────────
# Extraction Node (Digital-Only Mode)
# ──────────────────────────────────────────────
def extraction_node(state: GraphState):
    """
    Extract structured data from an invoice.
    Uses high-speed text-based LLM extraction from the layout-preserved text.
    """
    attempt = state["retry_count"] + 1
    logger.info(f"Extraction attempt {attempt}")

    llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", google_api_key=GOOGLE_API_KEY)
    parser = PydanticOutputParser(pydantic_object=InvoiceData)

    # Build the system prompt — include previous errors on retry
    system_content = SYSTEM_PROMPT
    if state.get("previous_errors"):
        system_content += RETRY_SUFFIX

    format_instructions = parser.get_format_instructions()
    system_text = system_content.replace("{format_instructions}", format_instructions)
    if state.get("previous_errors"):
        system_text = system_text.replace(
            "{previous_errors}",
            "\n".join(f"- {e}" for e in state["previous_errors"])
        )

    try:
        # ── Text path: construct messages directly to bypass ChatPromptTemplate brace parsing bug ──
        human_text = (
            f"Invoice Markdown:\n\n{state['raw_markdown']}\n\n"
            f"Vendor Hint: {state['vendor_hint'] or 'Unknown'}"
        )

        messages = [
            SystemMessage(content=system_text),
            HumanMessage(content=human_text)
        ]

        raw_response = llm.invoke(messages)
        result = parser.parse(raw_response.content)

        return {
            "extracted_data": result.model_dump(),
            "errors": []
        }
    except Exception as e:
        logger.error(f"Extraction error: {e}")
        return {
            "errors": [str(e)],
            "retry_count": state["retry_count"] + 1,
            "previous_errors": state.get("previous_errors", []) + [str(e)],
        }


# ──────────────────────────────────────────────
# Normalization Node (NEW)
# ──────────────────────────────────────────────
def normalization_node(state: GraphState):
    """
    Post-extraction cleanup and normalization:
    - Strip ₹ symbols and commas from amounts
    - Standardize GSTIN formatting (uppercase, strip spaces)
    - Derive state_code and PAN from GSTINs
    - Auto-detect supply_type from GSTIN state codes
    - Normalize date formats
    """
    data = state.get("extracted_data")
    if not data:
        return state

    data = dict(data)  # Make mutable copy

    # ── Normalize GSTINs ─────────────────────
    for gstin_field in ("vendor_gstin", "customer_gstin", "shipping_gstin"):
        val = data.get(gstin_field)
        if val and isinstance(val, str):
            cleaned = val.strip().upper().replace(" ", "")
            data[gstin_field] = cleaned

    # ── Derive state codes and PAN from GSTINs ──
    vendor_gstin = data.get("vendor_gstin") or ""
    customer_gstin = data.get("customer_gstin") or ""

    if len(vendor_gstin) == 15:
        data["vendor_state_code"] = vendor_gstin[:2]
        data["vendor_pan"] = vendor_gstin[2:12]
    if len(customer_gstin) == 15:
        data["customer_state_code"] = customer_gstin[:2]
        data["customer_pan"] = customer_gstin[2:12]

    # ── Auto-detect supply type ──────────────
    vendor_state = data.get("vendor_state_code", "")
    customer_state = data.get("customer_state_code", "")

    if vendor_state and customer_state:
        if vendor_state == customer_state:
            data["supply_type"] = SupplyType.INTRA_STATE.value
        else:
            data["supply_type"] = SupplyType.INTER_STATE.value
    elif data.get("supply_type") in (None, "", "UNKNOWN"):
        # Try to infer from tax breakup
        tax_breakup = data.get("tax_breakup", [])
        tax_types = set()
        for tb in tax_breakup:
            if isinstance(tb, dict):
                tax_types.add(tb.get("tax_type", "").upper())
        if "IGST" in tax_types and "CGST" not in tax_types:
            data["supply_type"] = SupplyType.INTER_STATE.value
        elif "CGST" in tax_types or "SGST" in tax_types:
            data["supply_type"] = SupplyType.INTRA_STATE.value

    # ── Normalize amounts (strip ₹, commas) ──
    amount_fields = [
        "total_taxable_amount", "total_tax_amount", "total_amount",
        "total_cgst", "total_sgst", "total_igst", "total_cess", "round_off",
    ]
    for field in amount_fields:
        val = data.get(field)
        if isinstance(val, str):
            cleaned = val.replace("₹", "").replace(",", "").replace(" ", "").strip()
            try:
                data[field] = float(cleaned)
            except (ValueError, TypeError):
                data[field] = 0.0

    # ── Normalize line item amounts ──────────
    for item in data.get("line_items", []):
        if isinstance(item, dict):
            for field in ("quantity", "rate", "discount", "taxable_value", "total", "cess_amount"):
                val = item.get(field)
                if isinstance(val, str):
                    cleaned = val.replace("₹", "").replace(",", "").replace(" ", "").strip()
                    try:
                        item[field] = float(cleaned)
                    except (ValueError, TypeError):
                        item[field] = 0.0

            for tax in item.get("taxes", []):
                if isinstance(tax, dict):
                    for tf in ("tax_rate", "tax_amount", "taxable_amount"):
                        val = tax.get(tf)
                        if isinstance(val, str):
                            cleaned = val.replace("₹", "").replace(",", "").replace(" ", "").strip()
                            try:
                                tax[tf] = float(cleaned)
                            except (ValueError, TypeError):
                                tax[tf] = 0.0

    # ── Normalize reverse_charge ─────────────
    rc = data.get("reverse_charge")
    if rc and isinstance(rc, str):
        rc_upper = rc.strip().upper()
        if rc_upper in ("YES", "Y", "TRUE"):
            data["reverse_charge"] = "Y"
        elif rc_upper in ("NO", "N", "FALSE"):
            data["reverse_charge"] = "N"

    logger.info("Normalization complete — supply_type=%s", data.get("supply_type"))
    return {"extracted_data": data}


# ──────────────────────────────────────────────
# Validation Node
# ──────────────────────────────────────────────
def validation_node(state: GraphState):
    """Validate the extracted data for sanity before returning."""
    data = state.get("extracted_data")
    if not data:
        return {"errors": state["errors"] + ["No data extracted"]}

    errors = []

    # Required fields check
    if not data.get("invoice_number"):
        errors.append("Missing invoice number")
    if not data.get("vendor_name"):
        errors.append("Missing vendor name")
    if data.get("total_amount", 0) <= 0:
        errors.append("Total amount is zero or negative")

    # Line items check
    line_items = data.get("line_items", [])
    if not line_items:
        errors.append("No line items found")

    # GSTIN format check
    for label, field in [("Vendor", "vendor_gstin"), ("Customer", "customer_gstin")]:
        gstin = data.get(field)
        if gstin and len(gstin) != 15:
            errors.append(f"{label} GSTIN '{gstin}' is not 15 characters")

    # Tax sanity — at least one tax entry should exist
    tax_breakup = data.get("tax_breakup", [])
    if not tax_breakup and line_items:
        has_item_taxes = any(
            item.get("taxes") for item in line_items if isinstance(item, dict)
        )
        if not has_item_taxes:
            errors.append("No tax information found in invoice")

    # Supply type consistency
    supply_type = data.get("supply_type", "UNKNOWN")
    if supply_type == "INTRA_STATE":
        # Should have CGST+SGST, not IGST
        if data.get("total_igst", 0) > 0 and data.get("total_cgst", 0) == 0:
            errors.append("Supply type is INTRA_STATE but only IGST found (expected CGST+SGST)")
    elif supply_type == "INTER_STATE":
        # Should have IGST, not CGST+SGST
        if data.get("total_cgst", 0) > 0 and data.get("total_igst", 0) == 0:
            errors.append("Supply type is INTER_STATE but only CGST+SGST found (expected IGST)")

    if errors:
        logger.warning(f"Graph validation failed: {errors}")
        return {
            "errors": state["errors"] + errors,
            "previous_errors": state.get("previous_errors", []) + errors,
            "retry_count": state["retry_count"] + 1,
        }

    return {"errors": []}


# ──────────────────────────────────────────────
# Router / Logic
# ──────────────────────────────────────────────
def should_retry(state: GraphState):
    """Decision edge: retry if there are errors and retry limit not reached."""
    if not state["errors"]:
        return "end"

    if state["retry_count"] >= 2:
        logger.error("Max retries reached. Failing.")
        return "end"

    logger.info("Retrying extraction...")
    return "extract"


# ──────────────────────────────────────────────
# Build the Graph (4 nodes)
# ──────────────────────────────────────────────
workflow = StateGraph(GraphState)

workflow.add_node("extract", extraction_node)
workflow.add_node("normalize", normalization_node)
workflow.add_node("validate", validation_node)

workflow.set_entry_point("extract")

workflow.add_edge("extract", "normalize")
workflow.add_edge("normalize", "validate")

workflow.add_conditional_edges(
    "validate",
    should_retry,
    {
        "extract": "extract",
        "end": END
    }
)

graph_app = workflow.compile()


# ──────────────────────────────────────────────
# Public API
# ──────────────────────────────────────────────
def parse_invoice(
    raw_markdown: str,
    vendor_hint: str | None = None,
) -> dict:
    """
    Parse invoice into structured data using LangGraph.

    Pipeline: extract → normalize → validate → [retry or end]

    Args:
        raw_markdown: Layout-preserved text from pdfplumber extraction.
        vendor_hint: Optional vendor name hint.

    Returns:
        A dict matching the InvoiceData schema.
    """
    logger.info("Starting LangGraph parsing pipeline...")

    initial_state: GraphState = {
        "raw_markdown": raw_markdown,
        "extracted_data": None,
        "errors": [],
        "retry_count": 0,
        "vendor_hint": vendor_hint,
        "previous_errors": [],
    }

    final_state = graph_app.invoke(initial_state)

    if not final_state["extracted_data"]:
        return {
            "invoice_number": None,
            "date": None,
            "vendor_name": vendor_hint,
            "vendor_address": None,
            "vendor_gstin": None,
            "vendor_state_code": None,
            "customer_name": None,
            "customer_address": None,
            "customer_gstin": None,
            "customer_state_code": None,
            "place_of_supply": None,
            "supply_type": "UNKNOWN",
            "reverse_charge": None,
            "line_items": [],
            "tax_breakup": [],
            "total_taxable_amount": 0.0,
            "total_cgst": 0.0,
            "total_sgst": 0.0,
            "total_igst": 0.0,
            "total_cess": 0.0,
            "total_tax_amount": 0.0,
            "round_off": 0.0,
            "total_amount": 0.0,
            "confidence_score": 0.0,
        }

    return final_state["extracted_data"]
